/**
 * Browser-local provenance for an exported capture.
 *
 * A Take Passport deliberately contains metadata only. It never uploads the
 * recording, avatar, camera frames, device ids, or microphone labels.
 */

export const TAKE_PASSPORT_SCHEMA = 'facial-xr.take-passport';
export const TAKE_PASSPORT_VERSION = 1 as const;

export type TakePassportTimestamp = Date | string | number;

export type TakePassportHashStatus = 'computed' | 'unavailable' | 'failed';

export type TakePassportIntegrityEvent = {
  /** ISO-8601 timestamp for the observed event. */
  at: string;
  /** A stable, dotted event name such as `recording.microphone-granted`. */
  type: string;
  /** Human-readable context. Keep personal data out of this field. */
  detail?: string;
};

export type TakePassportIntegrityEventInput = Omit<TakePassportIntegrityEvent, 'at'> & {
  at?: TakePassportTimestamp;
};

export type TakePassportCanvas = {
  width: number;
  height: number;
};

/**
 * A non-biometric summary of the tracker that produced a Facial XR take.
 * It intentionally excludes landmarks, blendshapes, calibration values, and
 * any individual face signal.
 */
export type TakePassportTracking = {
  provider: string;
  modelVersion?: string;
  mode?: string;
  actualFps?: number;
  targetFps?: number;
  droppedVideoFrames?: number;
};

/**
 * Deliberately excludes track label, deviceId, and groupId. Those values can
 * identify a person's hardware and are not needed to verify a capture.
 */
export type TakePassportCameraSettings = {
  width?: number;
  height?: number;
  frameRate?: number;
  aspectRatio?: number;
  facingMode?: string;
};

export type TakePassportMicrophoneSettings = {
  sampleRate?: number;
  sampleSize?: number;
  channelCount?: number;
  echoCancellation?: boolean | string;
  autoGainControl?: boolean;
  noiseSuppression?: boolean;
};

export type TakePassportTrack<TSettings> = {
  enabled: boolean;
  muted: boolean;
  readyState: MediaStreamTrackState;
  settings: TSettings;
};

export type TakePassport = {
  schema: typeof TAKE_PASSPORT_SCHEMA;
  version: typeof TAKE_PASSPORT_VERSION;
  captureId: string;
  timestamps: {
    manifestCreatedAt: string;
    captureStartedAt: string;
    captureEndedAt: string;
  };
  media: {
    selectedMimeType: string;
    blobByteLength: number;
    sha256: string | null;
    sha256Status: TakePassportHashStatus;
  };
  canvas: TakePassportCanvas;
  avatar: {
    sourceLabel: string;
  };
  tracking?: TakePassportTracking;
  tracks: {
    camera?: TakePassportTrack<TakePassportCameraSettings>;
    microphone?: TakePassportTrack<TakePassportMicrophoneSettings>;
  };
  integrityEvents: TakePassportIntegrityEvent[];
};

export type CreateTakePassportOptions = {
  /** The final recording blob to attest. */
  blob: Blob;
  /** The MediaRecorder MIME type selected before recording began. */
  selectedMimeType: string;
  /** Usually the canvas that supplied `captureStream()`. */
  canvas: TakePassportCanvas;
  /** Optional caller-supplied ID; a local random ID is generated by default. */
  captureId?: string;
  captureStartedAt?: TakePassportTimestamp;
  captureEndedAt?: TakePassportTimestamp;
  avatarSourceLabel?: string;
  /** Optional non-biometric tracker diagnostics for a Facial XR recording. */
  tracking?: TakePassportTracking;
  /**
   * Explicit tracks take precedence over `mediaStream`. This makes it
   * possible to attest a camera track separately from a composited canvas.
   */
  cameraTrack?: MediaStreamTrack | null;
  microphoneTrack?: MediaStreamTrack | null;
  /** A convenience for recordings whose video and audio tracks are combined. */
  mediaStream?: MediaStream | null;
  integrityEvents?: readonly TakePassportIntegrityEventInput[];
};

export type DownloadTakePassportOptions = {
  filename?: string;
};

type HashResult = {
  sha256: string | null;
  status: TakePassportHashStatus;
  error?: string;
};

const FALLBACK_MIME_TYPE = 'application/octet-stream';

const toIsoTimestamp = (
  value: TakePassportTimestamp | undefined,
  fallback: string,
): { value: string; wasInvalid: boolean } => {
  if (value === undefined) return { value: fallback, wasInvalid: false };

  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return { value: fallback, wasInvalid: true };

  return { value: date.toISOString(), wasInvalid: false };
};

const createCaptureId = (): string => {
  try {
    if (typeof globalThis.crypto?.randomUUID === 'function') {
      return `capture-${globalThis.crypto.randomUUID()}`;
    }
  } catch {
    // A fallback ID below keeps the feature usable in older browser contexts.
  }

  const entropy = Math.random().toString(36).slice(2, 12);
  return `capture-${Date.now().toString(36)}-${entropy}`;
};

const normalizeCanvasDimension = (value: number): number => {
  if (!Number.isFinite(value) || value < 0) return 0;
  return Math.floor(value);
};

const normalizeNonNegativeInteger = (value: number | undefined): number | undefined => {
  if (value === undefined || !Number.isFinite(value) || value < 0) return undefined;
  return Math.floor(value);
};

const normalizeTracking = (tracking: TakePassportTracking | undefined): TakePassportTracking | undefined => {
  if (!tracking?.provider?.trim()) return undefined;
  return {
    provider: tracking.provider.trim(),
    ...(tracking.modelVersion?.trim() ? { modelVersion: tracking.modelVersion.trim() } : {}),
    ...(tracking.mode?.trim() ? { mode: tracking.mode.trim() } : {}),
    ...(normalizeNonNegativeInteger(tracking.actualFps) !== undefined ? { actualFps: normalizeNonNegativeInteger(tracking.actualFps) } : {}),
    ...(normalizeNonNegativeInteger(tracking.targetFps) !== undefined ? { targetFps: normalizeNonNegativeInteger(tracking.targetFps) } : {}),
    ...(normalizeNonNegativeInteger(tracking.droppedVideoFrames) !== undefined ? { droppedVideoFrames: normalizeNonNegativeInteger(tracking.droppedVideoFrames) } : {}),
  };
};

const getTrackSettings = (track: MediaStreamTrack): MediaTrackSettings => {
  if (typeof track.getSettings !== 'function') return {};
  return track.getSettings();
};

const cameraSettingsFrom = (settings: MediaTrackSettings): TakePassportCameraSettings => ({
  ...(settings.width !== undefined ? { width: settings.width } : {}),
  ...(settings.height !== undefined ? { height: settings.height } : {}),
  ...(settings.frameRate !== undefined ? { frameRate: settings.frameRate } : {}),
  ...(settings.aspectRatio !== undefined ? { aspectRatio: settings.aspectRatio } : {}),
  ...(settings.facingMode !== undefined ? { facingMode: settings.facingMode } : {}),
});

const microphoneSettingsFrom = (settings: MediaTrackSettings): TakePassportMicrophoneSettings => ({
  ...(settings.sampleRate !== undefined ? { sampleRate: settings.sampleRate } : {}),
  ...(settings.sampleSize !== undefined ? { sampleSize: settings.sampleSize } : {}),
  ...(settings.channelCount !== undefined ? { channelCount: settings.channelCount } : {}),
  ...(settings.echoCancellation !== undefined ? { echoCancellation: settings.echoCancellation } : {}),
  ...(settings.autoGainControl !== undefined ? { autoGainControl: settings.autoGainControl } : {}),
  ...(settings.noiseSuppression !== undefined ? { noiseSuppression: settings.noiseSuppression } : {}),
});

const createTrackPassport = <TSettings>(
  track: MediaStreamTrack,
  settingsFrom: (settings: MediaTrackSettings) => TSettings,
  eventTime: string,
  events: TakePassportIntegrityEvent[],
): TakePassportTrack<TSettings> => {
  let settings: MediaTrackSettings = {};

  try {
    settings = getTrackSettings(track);
  } catch {
    events.push({
      at: eventTime,
      type: 'track.settings-unavailable',
      detail: `${track.kind} track settings could not be read.`,
    });
  }

  return {
    enabled: track.enabled,
    muted: track.muted,
    readyState: track.readyState,
    settings: settingsFrom(settings),
  };
};

const toHex = (buffer: ArrayBuffer): string => {
  const bytes = new Uint8Array(buffer);
  let result = '';
  for (const byte of bytes) result += byte.toString(16).padStart(2, '0');
  return result;
};

const computeSha256 = async (blob: Blob): Promise<HashResult> => {
  try {
    const subtle = globalThis.crypto?.subtle;
    if (!subtle || typeof subtle.digest !== 'function') {
      return { sha256: null, status: 'unavailable' };
    }

    const digest = await subtle.digest('SHA-256', await blob.arrayBuffer());
    return { sha256: toHex(digest), status: 'computed' };
  } catch (error) {
    return {
      sha256: null,
      status: 'failed',
      error: error instanceof Error ? error.message : 'Unknown digest error.',
    };
  }
};

/**
 * Creates a JSON-safe, browser-local provenance manifest for a completed
 * recording. The digest is over the exact final Blob supplied by the caller.
 */
export const createTakePassport = async (
  options: CreateTakePassportOptions,
): Promise<TakePassport> => {
  const manifestCreatedAt = new Date().toISOString();
  const captureStartedAt = toIsoTimestamp(options.captureStartedAt, manifestCreatedAt);
  const captureEndedAt = toIsoTimestamp(options.captureEndedAt, manifestCreatedAt);
  const events: TakePassportIntegrityEvent[] = (options.integrityEvents ?? []).map((event) => {
    const timestamp = toIsoTimestamp(event.at, manifestCreatedAt);
    return {
      at: timestamp.value,
      type: event.type,
      ...(event.detail ? { detail: event.detail } : {}),
    };
  });

  if (captureStartedAt.wasInvalid) {
    events.push({
      at: manifestCreatedAt,
      type: 'passport.invalid-start-timestamp',
      detail: 'The supplied capture start timestamp was invalid and was replaced.',
    });
  }
  if (captureEndedAt.wasInvalid) {
    events.push({
      at: manifestCreatedAt,
      type: 'passport.invalid-end-timestamp',
      detail: 'The supplied capture end timestamp was invalid and was replaced.',
    });
  }
  if (Date.parse(captureEndedAt.value) < Date.parse(captureStartedAt.value)) {
    events.push({
      at: manifestCreatedAt,
      type: 'passport.timestamp-order-warning',
      detail: 'Capture end precedes capture start; caller-provided values were preserved.',
    });
  }

  const cameraTrack = options.cameraTrack !== undefined
    ? options.cameraTrack
    : options.mediaStream?.getVideoTracks()[0];
  const microphoneTrack = options.microphoneTrack !== undefined
    ? options.microphoneTrack
    : options.mediaStream?.getAudioTracks()[0];
  const tracks: TakePassport['tracks'] = {};

  if (cameraTrack) {
    tracks.camera = createTrackPassport(cameraTrack, cameraSettingsFrom, manifestCreatedAt, events);
  }
  if (microphoneTrack) {
    tracks.microphone = createTrackPassport(microphoneTrack, microphoneSettingsFrom, manifestCreatedAt, events);
  }

  const hash = await computeSha256(options.blob);
  if (hash.status === 'computed') {
    events.push({ at: new Date().toISOString(), type: 'media.sha256-computed' });
  } else if (hash.status === 'unavailable') {
    events.push({
      at: new Date().toISOString(),
      type: 'media.sha256-unavailable',
      detail: 'Web Crypto is unavailable in this browser context.',
    });
  } else {
    events.push({
      at: new Date().toISOString(),
      type: 'media.sha256-failed',
      detail: hash.error,
    });
  }

  events.push({ at: new Date().toISOString(), type: 'passport.created' });

  const tracking = normalizeTracking(options.tracking);

  return {
    schema: TAKE_PASSPORT_SCHEMA,
    version: TAKE_PASSPORT_VERSION,
    captureId: options.captureId?.trim() || createCaptureId(),
    timestamps: {
      manifestCreatedAt,
      captureStartedAt: captureStartedAt.value,
      captureEndedAt: captureEndedAt.value,
    },
    media: {
      selectedMimeType: options.selectedMimeType.trim() || options.blob.type || FALLBACK_MIME_TYPE,
      blobByteLength: options.blob.size,
      sha256: hash.sha256,
      sha256Status: hash.status,
    },
    canvas: {
      width: normalizeCanvasDimension(options.canvas.width),
      height: normalizeCanvasDimension(options.canvas.height),
    },
    avatar: {
      sourceLabel: options.avatarSourceLabel?.trim() || 'Unknown avatar source',
    },
    ...(tracking ? { tracking } : {}),
    tracks,
    integrityEvents: events,
  };
};

/** Creates the standalone JSON file without initiating a download. */
export const takePassportToBlob = (passport: TakePassport): Blob => new Blob(
  [JSON.stringify(passport, null, 2)],
  { type: 'application/json;charset=utf-8' },
);

const sanitizeFilename = (value: string): string => {
  const normalized = value
    .trim()
    .replace(/[\\/:*?"<>|%]/g, '-')
    .replace(/\s+/g, '-')
    .replace(/^\.+/, '')
    .slice(0, 180);
  const fallback = normalized || 'take-passport';
  return fallback.toLowerCase().endsWith('.json') ? fallback : `${fallback}.json`;
};

/**
 * Downloads a Passport as a local JSON file. It returns false rather than
 * throwing in non-browser contexts, and delays object-URL revocation so
 * Safari has time to begin the download.
 */
export const downloadTakePassport = (
  passport: TakePassport,
  options: DownloadTakePassportOptions = {},
): boolean => {
  if (
    typeof document === 'undefined'
    || typeof URL === 'undefined'
    || typeof URL.createObjectURL !== 'function'
  ) {
    return false;
  }

  const url = URL.createObjectURL(takePassportToBlob(passport));
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = sanitizeFilename(options.filename ?? `take-passport-${passport.captureId}`);
  anchor.rel = 'noopener';
  anchor.style.display = 'none';
  document.body?.appendChild(anchor);
  anchor.click();
  anchor.remove();

  globalThis.setTimeout(() => URL.revokeObjectURL(url), 1_000);
  return true;
};
